### ISSUE TITLE
no quest reward freeze

### ISSUE THREAD

**Issue by dyrt1** [alfficcadenti/splinterlands-bot#29]
anyone know why itll get to scanning the quest say no quest reward to be claimed then never rollover to the next part... just freezes there.. like this
Login
Quest:  { name: 'Stealth Mission', splinter: 'sneak', total: 5, completed: 5 }
no quest reward to be claimed
[Error while waiting for battle]
Refreshing the page and retrying to retrieve a battle
[Battle cannot start]: TimeoutError: Navigation timeout of 30000 ms exceeded

**Comment by circle2014** [comment]
Same here.

**Comment by alfficcadenti** [comment]
It’s not an issue related to the quest but Download the latest code and the logs are more verbose so you understand better what’s going on
