### ISSUE TITLE
Error after Battle button clicked

### ISSUE THREAD

**Issue by phidang** [alfficcadenti/splinterlands-bot#50]
Hi,
I got the following error when running the bot. Could anyone help me out?
Thank you so much!

Battle button clicked
waiting for an opponent...
[Error while waiting for battle]
Refreshing the page and retrying to retrieve a battle
Battle button clicked
second attempt failed reloading from homepage...
[ERROR] waiting for Battle button second time
third attempt failed
[Battle cannot start]: Error: TimeoutError: waiting for selector `.btn--create-team` failed: timeout 50000ms exceeded
    at D:\splinterlands-bot-master\splinterlands-bot-master\index.js:131:35
    at async D:\splinterlands-bot-master\splinterlands-bot-master\index.js:127:21
    at async D:\splinterlands-bot-master\splinterlands-bot-master\index.js:117:13
    at async startBotPlayMatch (D:\splinterlands-bot-master\splinterlands-bot-master\index.js:106:9)
    at async D:\splinterlands-bot-master\splinterlands-bot-master\index.js:248:13
Error: The Battle cannot start
    at startBotPlayMatch (D:\splinterlands-bot-master\splinterlands-bot-master\index.js:136:15)
    at async D:\splinterlands-bot-master\splinterlands-bot-master\index.js:248:13

**Comment by Hsu-ken** [comment]
me too

**Comment by maximilianpace** [comment]
me too

**Comment by yvlasenko** [comment]
Most likely it means you're too aggressive on the API and get 429 during login
![2021-10-21 17 27 36](https://user-images.githubusercontent.com/531068/138359500-707a2614-f5af-4e08-9426-f5ce4c914cb0.jpg)
https://peakd.com/splinterlands/@splinterlands/splinterlands-updates-october-2021

**Comment by alfficcadenti** [comment]
it is possible. so the solutions are:
increase the time interval per battle
or download the latest code. This will makes 1 login and keep the browser open
