### ISSUE TITLE
Question about functionality

### ISSUE THREAD

**Issue by alek-tech** [alfficcadenti/splinterlands-bot#52]
Hi, i'm trying to recreate a version of the bot in python and since i'm not very familiar with JS i wondered if you could explain in short what logic are you using for the card selection, Best regards. Great project btw.

**Comment by alfficcadenti** [comment]
checking the history of other matches (where I save all the winning teams) and select the most winning team for a specific mana cap/ruleset...
the V2 I'm working on, includes also the winning rate of the team and not only the most used

**Comment by alek-tech** [comment]
Oh great, does that mean that you have a specific team for every possible mana cap/ruleset? And if so, would it be possible for you to somehow share these lists or shortly explain the functions to retrieve this info??  Thanks a lot and Best regards.

**Comment by alfficcadenti** [comment]
I provide access to private API with the V2 logic only to subscribers (the cost is 10$ a month per account)
