### ISSUE TITLE
battlesGetData. no longer seems to be pulling data

### ISSUE THREAD

**Issue by bwstandard** [alfficcadenti/splinterlands-bot#74]
When trying to pull data manually it says network response not ok, it worked yesterday without an issue.

**Comment by oscarb307** [comment]
I was able to get it to work by changing:
line 10 in battlesGetData.js to
`const battleHistory = await fetch('https://api2.splinterlands.com/battle/history?player=' + player)`

**Comment by alfficcadenti** [comment]
just pushed the new address as per @oscarb307 and i close the issue
