### ISSUE TITLE
fetch  FetchError: invalid json response

### ISSUE THREAD

**Issue by ralts00** [alfficcadenti/splinterlands-bot#81]
Hello, the robot shows this error, I don't know how to fix it, it didn't show it before
<img width="1341" alt="Captura de Pantalla 2021-11-11 a la(s) 10 16 10 a m" src="https://user-images.githubusercontent.com/5034252/141331834-2da29df8-f2ca-49ca-b325-0ec98b8bf0eb.png">
.

**Comment by dominiclapointe** [comment]
im having the exact same issue. I guess its related to the token=undefined in the call above... if anyone knows what the issue could ?

**Comment by bwstandard** [comment]
Same

**Comment by dominiclapointe** [comment]
@alfficcadenti are you comfortable sharing the code of the API? So we could help debug it?

**Comment by alfficcadenti** [comment]
the issue with the public api is the overloaded traffic. I offer private (paid) api for to who is keen to support the project

**Comment by dominiclapointe** [comment]
Ok thanks for the info, i can stop investigating on the issue then if its only a traffic issue ;)

Ill contact you in the upcoming days to see how we the private API works and how to support (gitcoin?).

Thank you
