### ISSUE TITLE
Bot not running anymore?

### ISSUE THREAD

**Issue by supershwa** [alfficcadenti/splinterlands-bot#96]
Before the last update a week or so ago, the bot was running smoothly without issue.

However, with the latest updates, I haven't been able to run it.  When I run "node index.js", I don't get any errors and it just goes right back to the command prompt.

I'm on Windows, and running the latest version of Node.js.  I've run "npm install" to install all of the dependency modules, including the latest puppeteer module.

Any ideas?

Thanks!

**Comment by alfficcadenti** [comment]
`npm start` instead of `node index.js`

**Comment by supershwa** [comment]
Aha - that did it!  Thank you.  Great bot!
